package com.luffyjet.gweb.mapper;

import com.luffyjet.gweb.model.Websites;
import com.luffyjet.gweb.model.WebsitesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WebsitesMapper extends BaseMapper<Websites>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table websites
     *
     * @mbg.generated Tue May 16 15:42:09 CST 2017
     */
    long countByExample(WebsitesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table websites
     *
     * @mbg.generated Tue May 16 15:42:09 CST 2017
     */
    int deleteByExample(WebsitesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table websites
     *
     * @mbg.generated Tue May 16 15:42:09 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table websites
     *
     * @mbg.generated Tue May 16 15:42:09 CST 2017
     */
    int insert(Websites record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table websites
     *
     * @mbg.generated Tue May 16 15:42:09 CST 2017
     */
    int insertSelective(Websites record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table websites
     *
     * @mbg.generated Tue May 16 15:42:09 CST 2017
     */
    List<Websites> selectByExample(WebsitesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table websites
     *
     * @mbg.generated Tue May 16 15:42:09 CST 2017
     */
    Websites selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table websites
     *
     * @mbg.generated Tue May 16 15:42:09 CST 2017
     */
    int updateByExampleSelective(@Param("record") Websites record, @Param("example") WebsitesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table websites
     *
     * @mbg.generated Tue May 16 15:42:09 CST 2017
     */
    int updateByExample(@Param("record") Websites record, @Param("example") WebsitesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table websites
     *
     * @mbg.generated Tue May 16 15:42:09 CST 2017
     */
    int updateByPrimaryKeySelective(Websites record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table websites
     *
     * @mbg.generated Tue May 16 15:42:09 CST 2017
     */
    int updateByPrimaryKey(Websites record);
}